import ClientOnly from "@/app/components/ClientOnly";
import Container from "@/app/components/Container";
import Header from "@/app/components/Header";
import type { Metadata } from "next";
import { Instrument_Sans, Instrument_Serif } from "next/font/google";
import "@/app/globals.css";

const instrumentSans = Instrument_Sans({
  weight: ["700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--custom-font-instrument_sans",
  display: "swap",
});
const instrumentSerif = Instrument_Serif({
  weight: ["400"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--custom-font-instrument_serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Jérôme Sembres | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${instrumentSans.variable}`}
      >
        <ClientOnly>
          <Container>
            <Header />
            {children}
          </Container>
        </ClientOnly>
      </body>
    </html>
  );
}
